hostPort: 127.0.0.1:1099
username: 
password: 
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["com.example.LogarithmResolver.jmx:*"]
rules:
  - pattern: '.*'
